[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
fix = true
select = ["E","F","I","UP","B","SIM"]
ignore = ["E501"]
exclude = ["node_modules","dist",".next",".venv"]

[tool.mypy]
python_version = "3.12"
warn_unused_ignores = true
ignore_missing_imports = true
strict_optional = true
