"""Add llm_api_keys to User model

Revision ID: 9ef3a14d78f5
Revises: b39b4d1e5233
Create Date: 2025-08-11 14:58:13.832401

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ef3a14d78f5"
down_revision: Union[str, Sequence[str], None] = "b39b4d1e5233"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("llm_api_keys", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "llm_api_keys")
    # ### end Alembic commands ###
